name: Web Audit Report
on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime to execute report audit, values: npm | bun | pnpm | yarn'
        default: 'npm'
        required: true
        type: string
env:
  REPORT_NAME: 'react-base-app'
jobs:
  audit:
    uses: ElJijuna/web-audit-report-action/.github/workflows/audit.yml@v1.0.0
    with:
      runtime: npm
      report_name: $REPORT_NAME
  publish-report:
    runs-on: ubuntu-latest
    needs: audit
    steps:
    - name: 📥 Cloning
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone --depth 1 https://x-access-token:${{ secrets.MONITORING_TOOL_DB }}@github.com/ElJijuna/MonitoringTool-DB.git .
    - name: 📥 Download artifact
      uses: actions/download-artifact@v4
      with:
        name: audit-report
    - name: 📂 Verify repository content
      run: ls -l
    - name: ✅ Commit & Push
      run: |
        git add $REPORT_NAME--web-audit.json
        git commit -m "📊 Update report"
        git push
